### PR TITLE
Fix blocking, add support of argument table

### LINKED ISSUE #12: Blocked publisher does not forward unblock message
When testing blocking/unblocking feature of cony, the publisher receives only the blocking message but not the unblocking/back to normal one.

To test the issue `rabbitmqctl set_vm_memory_high_watermark 0` puts the rabbit in alarm and `rabbitmqctl set_vm_memory_high_watermark 0.4` brings it back to normal.

PR to be provided soon.

### LINKED ISSUE #13: Support of headers in queue and exchange
All the declarations, Queue, Exchange and bindings, use `nil` as argument Table. It would be nice to add argument table to the structures and pass them to declaration to allow for exemple dead-lettering queue header.

### PR DESCRIPTION
**Pull request by sebastienfr**
Closes #12 blocking issue
Closes #13 support of header table

Refactor basic example to send messages at fixed rate to be able to test reconnection.

### CODE REVIEW

**Comment by kron4eg** [comment]
I'll review this

File: client.go [hunk 1]
```diff
@@ -134,20 +134,23 @@ func (c *Client) Loop() bool {
...
+				c.reportErr(err1)
+
+				if conn1 := c.conn.Load().(*amqp.Connection); conn1 != nil {
+					c.conn.Store((*amqp.Connection)(nil))
+					conn1.Close()
+				}
+				// return from routine to launch reconnect process
+				return
+			case blocking := <-chanBlocking:
+				c.blocking <- blocking
```
Comment (kron4eg) [inline client.go]: this will block forever in case if user is not reading `c.blocking`, previously it had fallback with default case

		case blocking := <-chanBlocking:
			select {
			case c.blocking <- blocking:
			default:
			}
		}

Comment (sebastienfr) [inline client.go]: Ok sorry, I was wondering what the purpose of the inner select was, it's fixed.

File: client.go [hunk 2]
```diff
@@ -134,20 +134,26 @@ func (c *Client) Loop() bool {
...
+
+				if conn1 := c.conn.Load().(*amqp.Connection); conn1 != nil {
+					c.conn.Store((*amqp.Connection)(nil))
+					conn1.Close()
+				}
+				// return from routine to launch reconnect process
+				return
+			case blocking := <-chanBlocking:
+				select {
+				case c.blocking <- blocking:
```
Comment (sebastienfr) [inline client.go]: So pushing in a channel that is full inside a select goes to default, is that right ?

**Comment by kron4eg** [comment]
LGTM, someone from @assembla/developers should merge this

**Comment by kolorowestudio** [comment]
[AAAAA](https://trello.com/c/Zbvdwvfm/56-aaaaa)
